### ISSUE TITLE
Album/collections help is not clear

### ISSUE THREAD

**Issue by Ailothaen** [voyageur/dagr#13]
Hi,

I tried dagr and I gotta say I'm enthusiastic about it, since none of the programs/scripts I tried before did work properly.

I have no problems downloading a whole gallery, but when I specify an album (with -a or -c option), the script finds only the first page of the folder (it detects 24 images whereas the folders I've tried had more).

Could you investigate the issue ?
Thanks in advance :)

**Comment by voyageur** [comment]
Thanks, interesting find! That is a situation I have not done in a loong time, I will take a look into it

**Comment by voyageur** [comment]
Picking one random collection:
http://adam-walker.deviantart.com/favourites/70659528/Dragons-and-monsters
it found 5 pages/109 images with:
dagr.py -v -c 70659528/Dragons-and-monsters adam-walker

Which version are you using? git master, last release?
Also it may be the pesky int before the gallery name that was missing

**Comment by Ailothaen** [comment]
Ah, actually I was using the -a option with only the gallery ID. Like that :
dagr.py -v -c 70659528 adam-walker
When I added the rest of the URL, the following pages loaded with no problems.

I guess this was just a mistake of myself ^^'
But however, the documentation for -a and -c options is not very clear (in the -h help we only see "-a, --album=#####", and we don't know what we should put instead of the #). So the -h should mention the exact syntax

**Comment by voyageur** [comment]
Indeed, some clearer help text for these options would really be great (and needed). Now to write something short and clear and helpful here...

**Comment by voyageur** [comment]
#14 is worth a new release, but I will first fix this too before tagging the next version
