### ISSUE TITLE
Reports that "{{username}}'s gallery had no deviations"

### ISSUE THREAD

**Issue by eldark** [voyageur/dagr#14]
No matter what user's gallery you try to rip, **dagr** reports that it does not have any deviations.
Example:

```
dagr.py v0.62 - deviantArt gallery ripper
Attempting to log in to deviantArt...
Logged in!
Current deviant: kahchan97
Ripping kahchan97's gallery...
kahchan97's gallery had no deviations.
```

Called with my **username** and **password**, and with **-gv** switches.

**Comment by Ailothaen** [comment]
Looks like I have the same problem...

**Comment by Jar4ek** [comment]
Mee to i have the sam problem. Please Help.

**Comment by kpuc** [comment]
The issue is DeviantART moved to https.  

If you find and replace all instances of http: with https:  dagr.py works again. 

Cheers

**Comment by eldark** [comment]
Thanks for the tip!

**Comment by Jar4ek** [comment]
Ohh Thanks You so much, for Tip. :)

**Comment by Jar4ek** [comment]
Thanks for Tip, but error pops up : 

> Download link not found, falling back to direct image
> Downloading 33 of 1496 ( https://stefangrosjean.deviantart.com/art/Shower-Room-115359825 )

Please help.

**Comment by kpuc** [comment]
Jar4ek:
I'm unable to reproduce that issue.  I tried the same gallery and most of the images don't have a Download link (so we get the "fallback" message), but a few do have the Download link, and do work.. 
https://stefangrosjean.deviantart.com/art/Coming-Out-471058909 for example, and https://stefangrosjean.deviantart.com/art/A-Rainstorm-Of-Freckles-496946405

I don't actually write python (I find it an annoying language), but I've put some effort into dagr.py..  In trying to reproduce your error I have discovered the script doesn't appreciate 404 on https://stefangrosjean.deviantart.com/art/A-New-Religion-323272314 :: the small image seems to 404, but clicking in the blank space displays the bigger image.  I will have to try to resolve this, too.

**Comment by Jar4ek** [comment]
@kpuc 
I understand, thank you so much for the help. I do not like python so much, so even if I wanted to, I do not have any help. As for the large work put into the dagr, I am I am indefinitely grateful for your effort and hard work. :)

Best Regards,
Jarek

**Comment by voyageur** [comment]
Funny one, the small image that 404s while there is a proper large one, this is probably worth a separate bug. For the other ones @kpuc said it all, the fallback method is the "best image we could find" even if sometimes small

In the meantime, back to original topic, thanks for the report and fix! I'll push an update to use HTTPS everywhere
