### ISSUE TITLE
Enhancements: existing files

### ISSUE THREAD

**Issue by jimhsu** [voyageur/dagr#15]
Hi, great script that says what it does. Two points:

Script is slow over a high latency connection especially when dealing with already downloaded files (using this as a sync tool). Can existing files in directory be listed and compared w gallery entries to speed things up when the overwrite flag is off?

2. Support for threading options? Obviously some sort of sane cap is advised. (_well, xargs technically takes care of this for multiple artists, so lower priority item_)

**Comment by voyageur** [comment]
Sorry for the delay, indeed I noticed both points quite a few times!

I splitted threading option in separate issue #20, as for general slowness, I am open to ideas:

from what I remember in the code, for each potential image we try different possible image locations, and once found, download it. Or skip it if name is identical.
* Do/can we know the image name earlier to skip some searches?
* Can we use alternative naming? (probably not easy, as page names may be duplicate, ...)
* Keep a list of already downloaded "items" somewhere?

**Comment by voyageur** [comment]
OK finally got a feasible solution. Checking on file name itself is not easy, as this file name is found after parsing the page.

Instead I added a few lines that will keep track (in a local JSON file per directory) of previously crawled pages. Once the file exists (need to re-run once to create it), only new pages will go through the loop.
