### ISSUE TITLE
Crash on gallery retrieval

### ISSUE THREAD

**Issue by Smannesman** [voyageur/dagr#16]
> Downloading 163 of 549 ( https://sandara.deviantart.com/art/desolate-199659377 )
> Traceback (most recent call last):
>   File "dagr.py", line 627, in <module>
>     main()
>   File "dagr.py", line 610, in main
>     ripper.deviant_get("gallery")
>   File "dagr.py", line 315, in deviant_get
>     mode + "/" + filename)
>   File "dagr.py", line 155, in get
>     str(self.browser.response.status_code))
> __main__.DagrException: incorrect status code: 404

**Comment by jimhsu** [comment]
Getting this too. Seems sporadic. Think it's occasional rate-limiting/timeouts. Better exception handling would be welcome (skip, or try file again later at end)

**Comment by Smannesman** [comment]
Ah that could be, it did happen after I downloaded a couple of galleries. I'll try it again tomorrow on the same gallery to see if that changes anything.

**Comment by jimhsu** [comment]
I made the following changes (not commiting this, as it's hacky and results in silent skipping of missing deviants):

On code beginning with:

```
        if self.browser.response.status_code != req_codes.ok:
            raise DagrException("incorrect status code: " +
                                str(self.browser.response.status_code))
```

Replace with 

```
        if self.browser.response.status_code != req_codes.ok:
            print("File not found! Status code: " + str(self.browser.response.status_code))
            #raise DagrException("incorrect status code: " +
            #                    str(self.browser.response.status_code))
```

**Comment by voyageur** [comment]
From what I see, deviantart is buggy for these images (page pointing to a non-existing image).

On a 404 error we should not die, instead skip them and report these errors (kind of like the current mature errors counter)
