### ISSUE TITLE
Not downloading original picture's name - "Download link not found, falling back to direct image"

### ISSUE THREAD

**Issue by JurajHanakovic** [voyageur/dagr#21]
Sometimes it's not downloading original picture's name.
Returining this: "Download link not found, falling back to direct image" and renaming picture to something generic like "img_6005_2_by_ghpart-d68dpho" or "untitled_by_ghpart-d7etyt1".
File downloads fine tho.

**Comment by voyageur** [comment]
Image file name is the basename from the found image URL, which may be different than the page name. This should also be the filename you get by opening the image directly.
https://ghpart.deviantart.com/art/Klara-3-406576653 for example, showing the image gives img_9871_3_by_ghpart-d6q2cjx.jpg

So in fact it does a good job of keeping the the original picture name :) (not sure but it is probably the original filename uploaded by the author)
For cases like this one, an option would be to use <page_name>.<original_extension> to get a name closer to the URL
