### ISSUE TITLE
Sometimes not downloading full-size pictures

### ISSUE THREAD

**Issue by JurajHanakovic** [voyageur/dagr#22]
Sometimes it doesn't download full-size pictures, only some thumbnail size or similar.
Without saying anything about it in command line.
Happens to most of the files I've tried to download.

**Comment by voyageur** [comment]
Is it on images without a download link (as in #21)? In that case there are 3 possible fallback methods, but this should get the biggest image possible. Do you have any examples?

Fallback has limited potential of course, but should find bigger images than thumbnails
