### ISSUE TITLE
Not able to download pics without specifying deviant username

### ISSUE THREAD

**Issue by yusuf-khaled** [voyageur/dagr#23]
It states I can get images based on query terms, but when I try this it says I must specify a deviant's username?

**Comment by voyageur** [comment]
Hi, indeed the script is focused on getting content from a specific deviant (galleries, queries, etc, ...). Sorry it is not clear in the help.

I guess the code could be used to navigate through https://www.deviantart.com/newest with a query, but not sure how it would go with many results
