### ISSUE TITLE
Had no deviations

### ISSUE THREAD

**Issue by mattjb1222** [voyageur/dagr#24]
Did something change? Or am I doing something incorrectly?

$ python --version
Python 2.7.14

$ python dagr.py -mgs ellysiumn
dagr.py v0.63 - deviantArt gallery ripper
Current deviant: Ellysiumn
Ripping Ellysiumn's gallery...
Ellysiumn's gallery page 1 crawled...
Total deviations in Ellysiumn's gallery found: 2
Ellysiumn's gallery successfully ripped.
Ripping Ellysiumn's scraps...
Ellysiumn's scraps page 1 crawled...
Total deviations in Ellysiumn's scraps found: 2
Ellysiumn's scraps successfully ripped.
Job complete.

$ python dagr.py -mgs jack-13
dagr.py v0.63 - deviantArt gallery ripper
Current deviant: Jack-13
Ripping Jack-13's gallery...
Jack-13's gallery had no deviations.
Ripping Jack-13's scraps...
Jack-13's scraps had no deviations.
Job complete.

**Comment by eldark** [comment]
It may have something to do with DeviantArt's change from **username.deviantart.com** to **deviantart.com/username**.

**Comment by mattjb1222** [comment]
You seem to be correct, eldark. I adjusted all instances of 'deviant', 'self.deviant', and 'self.deviant.lower()' in dagr.py to be after the ".com/" instead of after the "https://". Seems to be functioning with those changes.

**Comment by eldark** [comment]
Glad to help. Now let's hope @voyageur applies this fix.

**Comment by TinaRussell** [comment]
I’m getting this bug again. :frowning_face: I get “had no deviations” for any artist, and I’m using the latest version of dagr.py from git. Was there another change to DeviantArt?

**Comment by voyageur** [comment]
Changes at DeviantArt can always happen :/ I will check this some time next week (away from my dev box at the moment)

**Comment by voyageur** [comment]
@TinaRussell just retested some galleries download, 0.70.1 (current master) works fine here. Do you have a sample command that fails? Also recent code now uses MechanicalSoup instead of Robobrowser, maybe a bad installation of this module

```
% dagr.py -gv MimiReaves
dagr.py v0.70.1 - deviantArt gallery ripper
Current deviant: MimiReaves
Ripping MimiReaves's gallery...
MimiReaves's gallery page 1 crawled...
MimiReaves's gallery page 2 crawled...
MimiReaves's gallery page 3 crawled...
MimiReaves's gallery page 4 crawled...
MimiReaves's gallery page 5 crawled...
MimiReaves's gallery page 6 crawled...
MimiReaves's gallery page 7 crawled...
MimiReaves's gallery page 8 crawled...
MimiReaves's gallery page 9 crawled...
MimiReaves's gallery page 10 crawled...
MimiReaves's gallery page 11 crawled...
Total deviations in MimiReaves's gallery found: 251
Total deviations to download: 1
Downloading 1 of 1 ( https://www.deviantart.com/mimireaves/art/Gotham-City-Lovers-662363339 )
MimiReaves's gallery successfully ripped.
Job complete.
```
