### ISSUE TITLE
FileNotFoundError every time, perhaps an improper install

### ISSUE THREAD

**Issue by chrsmlls333** [voyageur/dagr#29]
Hi there,

First of all, I'm unsure if I installed this correctly, as I'm newish to python. Tried first through pip, but even after a successful install, it was not in my path, so `python dagr.py` never worked, with the module/package not being found. Tried again from source, which once again seemed to complete successfully with a build and dist folder being generated. 

After crawling any gallery, I consistently get a FileNotFoundError. Any info would be super helpful!!

```
~~~~ python -V
Python 2.7.14
~~~~ python dagr/dagr.py -mgs lucid-light
dagr.py v0.70 - deviantArt gallery ripper
Current deviant: lucid-light
Ripping lucid-light's gallery...
lucid-light's gallery page 1 crawled...
lucid-light's gallery page 2 crawled...
lucid-light's gallery page 3 crawled...
lucid-light's gallery page 4 crawled...
lucid-light's gallery page 5 crawled...
lucid-light's gallery page 6 crawled...
lucid-light's gallery page 7 crawled...
lucid-light's gallery page 8 crawled...
lucid-light's gallery page 9 crawled...
lucid-light's gallery page 10 crawled...
lucid-light's gallery page 11 crawled...
Total deviations in lucid-light's gallery found: 243
Traceback (most recent call last):
  File "dagr/dagr.py", line 548, in <module>
    main()
  File "dagr/dagr.py", line 531, in main
    ripper.deviant_get("gallery")
  File "dagr/dagr.py", line 318, in deviant_get
    self.get_images(mode, mode_arg, pages)
  File "dagr/dagr.py", line 256, in get_images
    except FileNotFoundError as fnf_error:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by voyageur** [comment]
Sorry for that, FileNotFoundError is python3 only (I know this now)! Short term fix is to replace it by IOError (the more generic, older class).
I will see before committing if a cleaner fix can be done, like checking some attributes in the exception.
But short term fix should be fine, and it is only used for the new feature to track already downloaded files.

**Comment by chrsmlls333** [comment]
Alrighty, I figured out how to install and run from python3 based on your comment so that's great in the meantime.

**Comment by voyageur** [comment]
Good to know! As the exception in itself is not important, the fix is not too big anyway, pushing it now. Should work in both python 2 and 3
