### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by eldark** [voyageur/dagr#33]
I'm receiving this error while trying to use it with no username/password:

`
dagr.py v0.70.1 - deviantArt gallery ripper

Current deviant: Satomi-Tadashi

Ripping Satomi-Tadashi's gallery...

Satomi-Tadashi's gallery page 1 crawled...

Satomi-Tadashi's gallery page 2 crawled...

Satomi-Tadashi's gallery page 3 crawled...

Satomi-Tadashi's gallery page 4 crawled...

Total deviations in Satomi-Tadashi's gallery found: 87

Total deviations to download: 87

Downloading 1 of 87 ( https://www.deviantart.com/satomi-tadashi/art/Junko-Kurosu-100341362 )

Traceback (most recent call last):

  File "dagr.py", line 549, in <module>

    main()

  File "dagr.py", line 532, in main

    ripper.deviant_get("gallery")

  File "dagr.py", line 319, in deviant_get

    self.get_images(mode, mode_arg, pages)

  File "dagr.py", line 280, in get_images

    self.get(filelink, base_dir + "/" + filename)

  File "dagr.py", line 138, in get

    local_file = open(file_name, "wb")

IOError: [Errno 36] File name too long: u'/home/eldark/downloads/dagr/Satomi-Tadashi/gallery/file?downloadToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTU0MTQyMTcyMSwiaWF0IjoxNTQxNDIxMTExLCJqdGkiOiI1YmUwMzg0MWM4OTkyIiwib2JqIjpudWxsLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdLCJwYXlsb2FkIjp7InBhdGgiOiJcL2ZcLzEzOWJjMGQ3LWE0ZmMtNDVkYy04NTQ1LTc0Yjg3MjM2M2VlYVwvZDFucW53Mi05MmY0ZTljOC05ZDA4LTQ1YzMtYTRjOC04NDI3ZmI5MTBiNWMuanBnIn19.wQ-HqxpbDjFLfMsqIsIfNSfKSTgJEoxJU7aTf8mcJeg'
`

EDIT: CentOS Linux release 7.5.1804

**Comment by rickjthree** [comment]
Just to verify, I am also seeing this, both on a windows 7 box using cygwin and on a Centos 7.5 machine.

**Comment by eldark** [comment]
I'm seeing this on a CentOS machine too. I will add this to the first message.

**Comment by RarogCmex** [comment]
It's happened on my Gentoo mashine too

**Comment by eldark** [comment]
Solved in my environment!

**Comment by voyageur** [comment]
You can thank @GenMinusThree in #32 for the performance enhancement!

Now this current code downloads pictures again, but filename still needs to be fixed. One option would be to find it in the "collect_rid" links (even when using download button or meta) where it seems to be always available (some pictures do not have id in meta).
Another would be to switch image names to last part of URL (after /art) + extension.

**Comment by kannabianka** [comment]
When I download pictures by hand in the last few days, I rename the file using the name of one of the smaller version, which are different, and are almost correct (they end with -pre of -fullview).
But I think that like @voyageur said, it's simpler to take the last part of the url.

Thanks for your care!

**Comment by kannabianka** [comment]
Ok, tried the code right now.
Besides the filenames, this solves also issue #34 !!

**Comment by tdpage** [comment]
I'm having this issue. I guess DA really likes to make changes that break things here.

**Comment by Ailothaen** [comment]
I have the same problem (except that, for me, I have the "No such file or directory" error, such as the one in #34 ). I'm using the latest version (v0.70.1)

**Comment by voyageur** [comment]
I finally had some time to fix the filenames, going the "use the last part of URL as base for filename" way. I will push this soon and tag a new release

**Comment by voyageur** [comment]
Sigh, indeed the recent changes do not work on python2. Thanks for checking, I will open a new issue

**Comment by GenMinusThree** [comment]
Guess I am bit late on this, but noticed DA now properly provides name on clicking download button in browser. I checked the headers, and filename is provided in 'Content-Disposition' header. So it is possible to get original filename with get_resp.headers.get('Content-Disposition'))  in get function, and discarding part of string before and including '' .
Basically you get 
attachment; filename*=UTF-8''image_name_by_artist_id.png
