### ISSUE TITLE
NoneType found (usually .html type file)

### ISSUE THREAD

**Issue by mdagajew** [voyageur/dagr#36]
When using a script, sometimes there is such an error,
the file without the extension is saved, the script interrupts the operation and the following information appears:

"Traceback (last connection last call):
   File "/usr/local/bin/dagr.py", line 572, in <module>
     main ()
   File "/usr/local/bin/dagr.py", line 555, in main
     ripper.deviant_get ("gallery")
   File "/usr/local/bin/dagr.py", line 342, in deviant_get
     self.get_images (mode, mode_arg, pages)
   File "/usr/local/bin/dagr.py", line 303, in get_images
     self.get (filelink, base_dir + "/" + filename)
   File "/usr/local/bin/dagr.py", line 160, in get
     get_resp.headers.get ("content-type")))
TypeError: coercing to Unicode: need string or buffer, NoneType found "

Usually, you just have to give the .html extension to the last file downloaded, and it still works until the next occurrence of such an error.
Would not it be possible to add (correct) that if it finds a file without an extension, it would add a .html extension to it by default?

**Comment by blackpawninja** [comment]
i'm having similar problem and made a fix. hopefully it gets accepted soon

in the meantime, you can install my fork using
```
pip install --upgrade git+git://github.com/blackpawninja/dagr.git
```
and see if it fix your problem as well

**Comment by phillmac** [comment]
mimetypes also doesn't handle `'content_type': 'image/vnd.adobe.photoshop'`
see #39

**Comment by voyageur** [comment]
Should be fixed with all recent changes hopefully!
