### ISSUE TITLE
Crash when guess_extension() returns None

### ISSUE THREAD

**Issue by blackpawninja** [voyageur/dagr#37]
some gallery would crash with the following error
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\dagr.py", line 572, in <module>
    main()
  File "C:\Program Files (x86)\Python37-32\Scripts\dagr.py", line 555, in main
    ripper.deviant_get("gallery")
  File "C:\Program Files (x86)\Python37-32\Scripts\dagr.py", line 342, in deviant_get
    self.get_images(mode, mode_arg, pages)
  File "C:\Program Files (x86)\Python37-32\Scripts\dagr.py", line 303, in get_images
    self.get(filelink, base_dir + "/" + filename)
  File "C:\Program Files (x86)\Python37-32\Scripts\dagr.py", line 160, in get
    get_resp.headers.get("content-type").split(";")[0]))
TypeError: can only concatenate str (not "NoneType") to str
```

i trace the problem down to `guess_extension()` returns `None`. the error above is when downloading file with _content-type_ of `application/rar` in my windows machine

i think this issue also causes #36

**Comment by mdagajew** [comment]
After your corrections, do not crash.
Thanks
There is another thing that could be improved, in some galleries there are animations in .swf format that are reported as "maybe not an image" (which is true :-)) but maybe it would be possible to extend the download of these files. The same applies to the .psd and .tif files placed in the galleries.

**Comment by blackpawninja** [comment]
do you have the links to galleries that contains those files so i can test?

**Comment by voyageur** [comment]
> do you have the links to galleries that contains those files so i can test?

+1, a sample user would help to test that case. In theory, if there is a download button you should get the file (whatever its type). SWF may be tricky as they can be displayed directly in browser so may skip the download button

**Comment by phillmac** [comment]
Also had one with a `content-type: binary/octet-stream` when infact it was a png. most odd

**Comment by phillmac** [comment]
Re: binary/octet-stream
https://github.com/aws/aws-sdk-java/issues/1143
Pretty sure DA wasrunning some kind of AWS backend at some point. Dunno if they are anymore.

**Comment by phillmac** [comment]
Re:  @mdagajew  's swf files not working: made pr #40
Found an actual case where this was an issue.
Example user: https://www.deviantart.com/bagging *NSFW CONTENT*
There's no actual nudity in the linked user, but some fethishwear photography. its marked as mature, so thought id better warn anyhow.
