### ISSUE TITLE
DeviantArt returns only .jpe files

### ISSUE THREAD

**Issue by chrsmlls333** [voyageur/dagr#44]
Version 0.71.3 on Python 2.7.15rc1 on Ubuntu

I've noticed that all files are being downloaded as .jpe files instead of jpg or jpeg. Anyone else noticing this behaviour? Is this a typo or a quirk of deviantArt? 

Is there a way to add a rename function into dagr so I dont have to do a batch convert operation after the fact? Its not the end of the world but definitely seems like a bug.

**Comment by allthemikeysaretaken** [comment]
@chrsmlls333 

> Anyone else noticing this behaviour? Is this a typo or a quirk of deviantArt?

I ran this usng python 3.5.2 on mac OS 10.13.6 (High Sierra); all of my images are also saved as .jpe files, though they are still recognized as jpeg images.

**Comment by phillmac** [comment]
It's a result of the way the python mimetypes library handles things; the .jpe entry in the db is before the .jpg or .jpeg entries. Perhaps, if you have a look at `/etc/mime.types` and remove the .jpe entry it will fix your problem.

**Comment by RarogCmex** [comment]
>/etc/mime.types
Edited, but I still get .jpe

**Comment by Aidolii** [comment]
Change this line: `file_ext = guess_extension(content_type)`

to this: `file_ext = guess_extension(content_type).replace('jpe','jpg') if guess_extension(content_type) else guess_extension(content_type)`

**Comment by RarogCmex** [comment]
> Change this line: `file_ext = guess_extension(content_type)`
> 
> to this: `file_ext = guess_extension(content_type).replace('jpe','jpg') if guess_extension(content_type) else guess_extension(content_type)`
> 
> It's a bit long for a one-liner, but as a DIY fix, there's less chance of user error.

Thank you, Aidolii

**Comment by voyageur** [comment]
Yes, this is unfortunate that the module picks the first possible extension, and does not have a "preferred" one (jpe is apparently perfectly legal, but I have seldom seen files with it).

I am pushing a variation on that workaround (with separate function), it is a bit ugly, but better to use standard extensions...
