### ISSUE TITLE
Backend change breaking everything

### ISSUE THREAD

**Issue by God-damnit-all** [voyageur/dagr#48]
`python dagr.py -g yacrical`

```
dagr.py v0.71.3 - deviantArt gallery ripper
Traceback (most recent call last):
  File "dagr.py", line 608, in <module>
    main()
  File "dagr.py", line 563, in main
    re.IGNORECASE).group(0)[7:]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ImportTaste** [comment]
Ah. I see what the problem is. You can no longer get to the old website design by changing your User Agent.

This will probably mean that the script will have to be adapted to using a session_id cookie of a logged in user with 'Eclipse' turned off until it can be made to work on this new design.

**Comment by God-damnit-all** [comment]
I see the problem. You can no longer get to the old website design via changing the user-agent. Unfortunately what is probably the best course of action is turning the new site design (Eclipse) off on your account, and then making dagr.py use your userinfo and auth keys from your cookies. It's a pretty long string though, so this necessitates having to use an ini file.

As a temporary DIY workaround, you can add `session.cookies.update({'userinfo': 'YOURAUTHCOOKIEVALUE'})` and `session.cookies.update({'userinfo': 'YOURAUTHCOOKIEVALUE'})` to dagr.py right after `session = req_session()`.

Additionally, to continue downloading pictures marked as mature, change `session.cookies.update({'agegate_state': '1'})` to `session.cookies.update({'_gat': '1'})`

EDIT: One more revision is needed, since this can apparently be a null value now: https://github.com/voyageur/dagr/blob/36c1751f3dbebb3f660d028e70707ebcd365c137/dagr/dagr.py#L231-L234
```
        if not current_page.find(
                "span", {"itemprop": "title"}).text != "Literature":
            filelink = self.browser.get_url()
            return (filename, filelink)
```

**Comment by kannabianka** [comment]
The research in the <title> tag at line 563 fails because there's no more the simple <title> tag but now there are some attributes.
I tried fixing the line, the script goes on, but ends in a loop while browsing the galleries...
So.. I have the same problem and no solution

**Comment by God-damnit-all** [comment]
@kannabianka I got it working. Apparently in addition to adding userinfo you must now also add the auth cookie. The auth_secure cookie doesn't seem to be needed for some reason. (Yet?) Oh, and there's another modification you have to do to get mature entries working again. I updated my previous comment with the new info.

Also, make sure to close out of deviantart immediately after getting these values, browsing the site kept making them change on me.

**Comment by Ailothaen** [comment]
Noticed that as well just now. It seems that now, the gallery of users (and by extension, anything that features more than some lines of content) is being lazy-loaded with infinite scroll, as you scroll down the page. I'm actually interested in how a script like that would be able to cope with JS: is that easy, or even possible?

**Comment by God-damnit-all** [comment]
There are certainly ways. [ChromeController](https://github.com/fake-name/ChromeController), for instance, gets around the issue by just using an actual browser, but completely in the background with as low of a footprint as possible.

**Comment by RarogCmex** [comment]
Ok, If you're fixing that can you made pull request? So I could be updated ;)

**Comment by God-damnit-all** [comment]
@RarogCmex My method is going to require reading from a file, because the cookies are far too long for the command line. I don't really know python to do that, so no PR.

**Comment by Ssurgul** [comment]
So, for those of us that aren't quite Python nor auth cookie ghods yet, when you say you'll need a file for the session.cookies.update lines, what do I need to assemble, and from where on my system? It's giving me the following error:

  File "dagr.py", line 144
    session.cookies.update({'userinfo': 'YOURAUTHCOOKIEVALUE'})
                                                              ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by God-damnit-all** [comment]
@Ssurgul It means what it says. Space/tab usage is important in Python. Make sure the code you've inserted has the same amount of spaces as the last relevant line of code before it. Also, 'YOURAUTHCOOKIEVALUE' is a placeholder.

**Comment by RarogCmex** [comment]
@ImportTaste so I had to wait mr. Voyageour

**Comment by UMLAUTaxl** [comment]
@ImportTaste 
1. Why do you write that I have to put the cookie line twice in there?
> session.cookies.update({'userinfo': 'YOURAUTHCOOKIEVALUE'}) and session.cookies.update({'userinfo': 'YOURAUTHCOOKIEVALUE'})

2. How do I switch to old design? I'm an "old user" so I guess I'm still on old design anyway.

3. It doesn't work I still get the same error like OP. 

(JDownloader also seems to struggle with the new design.)

**Comment by Ailothaen** [comment]
Hello,
I had a look at the Deviantart APIs: https://www.deviantart.com/developers/
The endpoints look actually quite complete, and could be a nice (and clean) solution for this problem.
Has the dagr project already considered using the API, and if yes, what was the reason why it was not actually used?

**Comment by MangaD** [comment]
Hello, just wanted to correct @ImportTaste's fix (thank you for it!), as the copy paste seems to have failed for him. 

After `session = req_session()`, you should add:
```py
session.cookies.update({'userinfo': 'YOUR_USERINFO_COOKIE_VALUE'})
session.cookies.update({'auth': 'YOUR_AUTH_COOKIE_VALUE'}) 
```
to `dagr.py`.

**Comment by UMLAUTaxl** [comment]
Now it crawls but doesn't download: #49
