### ISSUE TITLE
Sometimes not downloading full sizes

### ISSUE THREAD

**Issue by eldark** [voyageur/dagr#6]
Hi, @voyageur. I have noticed that sometimes **dagr** does not download full-sized pictures, but the smaller preview ones. I suspect this is the case for full-sized pictures without **Download** button (the ones you have to make three mouseclicks to see the original image). As soon as I can give you an example I will post it here, but I wanted to report this behaviour for future reference.

**Comment by voyageur** [comment]
No problem with 0.60 so far, don't hesitate to reopen if there are still some problematic pages!
