### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by voyageur** [voyageur/dagr#9]
Add a portable way to store configuration. This would be great for some parameters, mostly login/password

**Comment by eldark** [comment]
You could use a **settings.ini** file, or something like that:
```
[DeviantArt]
Username: username
Password: password
[Paths]
DownloadPath: /path/to/destination
```

And then parse that configuration file with **ConfigParser**:
```
import ConfigParser
def main():
    Config = ConfigParser.ConfigParser()
    Config.read('settings.ini')
    path = Config.get('Paths', 'DownloadPath')
    ripper.username = Config.get('DeviantArt', 'Username')
    ripper.password = Config.get('DeviantArt', 'Password')
    ...
```

**Comment by voyageur** [comment]
Indeed, not too big of a code chunk, I just had to find some time and motivation to finally add it. Thanks for the push!
